start_command:
  welcome_text: |
    Привет!  Я бот «Докопался!», и я помогу вам быстро проверить достоверность информации.

    <b>Что я умею:</b>
    • Анализирую тексты и пересланные посты из Telegram
    • Выделяю ключевые утверждения (до трех).
    • Ищу подтверждения или опровержения в надёжных источниках
    • Предоставляю результаты с анализом и ссылками на источники

    <b>Как использовать:</b>
    • Отправьте мне текст или перешлите Telegram-пост (важно: я не принимаю ссылки)
    • Получите анализ с подробной проверкой фактов
    • Поделитесь впечатлениями через @teplica_feedback_bot

    Сомневаетесь в утверждении друга или увидели подозрительную новость? Отправьте их мне, и я помогу докопаться до правды!

    <i>Важно: Я работаю на базе нейросетей, поэтому возможны небольшие ошибки. Команда Теплицы активно работает над улучшением моей точности.</i>

    P.S. Рекомендую также попробовать бот «Насквозь» @naskvos_bot — он поможет распознать эмоциональные манипуляции в сообщениях.

info_command:
  info_text: |
    <b>Докопался!</b> — это проект Теплицы социальных технологий https://te-st.org/, озданный для борьбы с дезинформацией и повышения медиаграмотности.

    <b>Цель проекта</b> — помочь вам быстро проверять достоверность информации, не тратя часы на самостоятельные поиски. Бот анализирует утверждения, тексты или Telegram-посты, которые вы ему присылаете, выделяет ключевые утверждения и ищет их подтверждение или опровержение в надёжных источниках.

    <b>Как это работает:</b>
    • Бот выделяет до трёх главных утверждений из текста
    • Проводит поиск в интернете
    • Возвращает результаты с анализом и ссылками на источники

    Используйте «Докопался!», когда сомневаетесь в достоверности информации или хотите составить сбалансированное мнение по интересующему вопросу.

    <i>Важно: Бот работает на базе нейросетей, поэтому возможны небольшие ошибки. Мы активно дорабатываем его на основе ваших отзывов — делитесь впечатлениями через @teplica_feedback_bot</i>

    «Докопался!» — часть серии инструментов Теплицы для борьбы с пропагандой и дезинформацией, наряду с ботами «Насквозь» (https://t.me/naskvos_bot) и «Сканер нарративов» (https://narrative.oplot.team/).

fact_check:
  no_claims: "Результаты проверки фактов:\nНе обнаружено фактических утверждений в вашем сообщении."
  claims_found_single: "Мы проанализировали отправленный текст и извлекли следующее ключевое утверждение:\n\n"
  claims_found_multiple: "Мы проанализировали отправленный текст и извлекли следующие ключевые утверждения:\n\n"
  checking_continue: "\nПродолжаем проверку..."
  results_header: "Результаты проверки утверждений:"
  unknown_source: "Неизвестный источник"
  verdict_label: "<b>Вердикт:</b>"
  source_label: "<b>Источник:</b>"
  conclusion_label: "<b>Заключение:</b>"
  sources_header: "<b>Источники:</b>"
  no_info: "⚠️ Нет достоверной информации."

other_commands:
  default_response: "Я не понимаю эту команду. Попробуйте /start, чтобы узнать, что я умею." 