start_command:
  welcome_text: |
    Привет! Я бот ФактЧекер, и моя задача — помочь тебе проверять достоверность утверждений и текстов с помощью машинного обучения.

    <b>Что я умею:</b>
    • Проверяю утверждения, тексты и посты в Telegram на достоверность.
    • Предоставляю результаты проверки с подробной информацией о проверенных источниках.

    <b>Как использовать:</b>
    • Отправь мне текст или Telegram-пост.
    • Получи проверку фактов и убедись в достоверности информации.

    Учти, что я работаю на базе машинного обучения и могу иногда ошибаться.

    Кстати, у нас есть ещё один полезный бот — «Насквозь» @naskvos_bot. Он помогает распознавать эмоциональные манипуляции в сообщениях и новостях. Попробуйте его, чтобы стать более уверенными в том, что вас не вводят в заблуждение.

info_command:
  info_text: |
    <b>Проект ФактЧекер</b> создан для повышения медиаграмотности и борьбы с медиа грамотности недостоверных сведений.

    <b>Цель проекта</b> — предоставить удобный инструмент для проверки фактов с помощью машинного обучения, чтобы каждый мог убедиться в достоверности информации и не стать жертвой ложных новостей.

    Используй ФактЧекер для того, чтобы получать только проверенные данные и бороться с ложной информацией в сети!
    <b>NB!</b> Учти, что я работаю на базе машинного обучения и могу иногда ошибаться.

fact_check:
  no_claims: "Результаты проверки фактов:\nНе обнаружено фактических утверждений в вашем сообщении."
  claims_found_single: "Мы проанализировали отправленный текст и извлекли следующее ключевое утверждение:\n\n"
  claims_found_multiple: "Мы проанализировали отправленный текст и извлекли следующие ключевые утверждения:\n\n"
  checking_continue: "\nПродолжаем проверку..."
  results_header: "Результаты проверки утверждений:"
  unknown_source: "Неизвестный источник"
  verdict_label: "<b>Вердикт:</b>"
  source_label: "<b>Источник:</b>"
  conclusion_label: "<b>Заключение:</b>"
  sources_header: "<b>Источники:</b>"
  no_info: "⚠️ Нет достоверной информации."

other_commands:
  default_response: "Ответ на другие команды" 